[files]
extend-exclude = [
  "*.lock",
  "*.log",
  "node_modules",
  ".venv",
  "staticfiles",
  "media",
  "backend",
  "hamirilo-platform",
  "claude-design",
  "static/dist"
]

[default.extend-words]
feedee = "feedee"
hamirilo = "hamirilo"
categor = "categor"
