# Generated by Django 5.2.12 on 2026-07-29 13:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rssapp', '0018_feed_is_public'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(blank=True, max_length=2048, null=True)),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('thumbnail_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('order', models.IntegerField(default=0)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'reading_items',
            },
        ),
        migrations.CreateModel(
            name='SomedayItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(blank=True, max_length=2048, null=True)),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('thumbnail_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'someday_items',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(blank=True, max_length=500, null=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'subscriptions',
            },
        ),

        migrations.AlterField(
            model_name='bookmark',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookmarks', to='rssapp.category'),
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published_at', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='articleuserstate',
            options={},
        ),
        migrations.AlterModelOptions(
            name='bookmark',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='bookmarkuserstate',
            options={},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['display_order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='extractiontask',
            options={},
        ),
        migrations.AlterModelOptions(
            name='feed',
            options={'ordering': ['display_order', 'name', 'title']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='articleuserstate',
            name='uniq_article_user_state',
        ),
        migrations.RemoveConstraint(
            model_name='bookmark',
            name='uniq_user_bookmark_url',
        ),
        migrations.RemoveConstraint(
            model_name='bookmark',
            name='uniq_user_bookmark_normalized_url',
        ),
        migrations.RemoveConstraint(
            model_name='bookmarkuserstate',
            name='uniq_bookmark_user_state',
        ),
        migrations.RemoveConstraint(
            model_name='category',
            name='uniq_user_category_name',
        ),
        migrations.RemoveConstraint(
            model_name='tag',
            name='uniq_user_tag_slug',
        ),
        migrations.RemoveIndex(
            model_name='articleuserstate',
            name='rssapp_arti_user_id_2cef78_idx',
        ),
        migrations.RemoveIndex(
            model_name='articleuserstate',
            name='rssapp_arti_user_id_d1de33_idx',
        ),
        migrations.RemoveIndex(
            model_name='articleuserstate',
            name='rssapp_arti_user_id_a28ea4_idx',
        ),
        migrations.RemoveIndex(
            model_name='bookmark',
            name='rssapp_book_user_id_18c12c_idx',
        ),
        migrations.RemoveIndex(
            model_name='bookmark',
            name='rssapp_book_user_id_d4e463_idx',
        ),
        migrations.RemoveIndex(
            model_name='bookmark',
            name='rssapp_book_user_id_b7a0da_idx',
        ),
        migrations.RemoveIndex(
            model_name='bookmarkuserstate',
            name='rssapp_book_user_id_d00b95_idx',
        ),
        migrations.RemoveIndex(
            model_name='bookmarkuserstate',
            name='rssapp_book_user_id_d3bc7e_idx',
        ),
        migrations.RemoveIndex(
            model_name='bookmarkuserstate',
            name='rssapp_book_user_id_d9b094_idx',
        ),
        migrations.RemoveIndex(
            model_name='extractiontask',
            name='rssapp_extr_status_67e350_idx',
        ),
        migrations.RemoveIndex(
            model_name='extractiontask',
            name='rssapp_extr_status_cae9c2_idx',
        ),
        migrations.RemoveField(
            model_name='article',
            name='content_source',
        ),
        migrations.RemoveField(
            model_name='article',
            name='extracted_at',
        ),
        migrations.RemoveField(
            model_name='article',
            name='extraction_status',
        ),
        migrations.RemoveField(
            model_name='article',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='articleuserstate',
            name='is_favorite',
        ),
        migrations.RemoveField(
            model_name='articleuserstate',
            name='is_read_later',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='category_v2',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='hash',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='normalized_url',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='source_article',
        ),
        migrations.RemoveField(
            model_name='bookmarkuserstate',
            name='is_favorite',
        ),
        migrations.RemoveField(
            model_name='bookmarkuserstate',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='bookmarkuserstate',
            name='is_read_later',
        ),
        migrations.RemoveField(
            model_name='category',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='extractiontask',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='extractiontask',
            name='started_at',
        ),
        migrations.RemoveField(
            model_name='extractiontask',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='category_v2',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='consecutive_failures',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='fetch_interval_minutes',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='last_error',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='last_success_at',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='next_fetch_at',
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='article',
            name='url',
            field=models.URLField(default='', max_length=2048),
        ),
        migrations.AddField(
            model_name='article',
            name='url_hash',
            field=models.CharField(db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='articleuserstate',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='articleuserstate',
            name='is_favorited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='bookmark_type',
            field=models.CharField(choices=[('resource', 'Resource'), ('content', 'Content')], default='content', max_length=20),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookmarkuserstate',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='bookmarkuserstate',
            name='is_favorited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='scope',
            field=models.CharField(choices=[('rss', 'RSS'), ('bookmark', 'Bookmark')], default='rss', max_length=20),
        ),
        migrations.AddField(
            model_name='feed',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='feed',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feed',
            name='favicon_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='feed',
            name='fetch_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feed',
            name='site_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='feed',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='feed',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tag',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='article',
            name='guid',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='link',
            field=models.URLField(default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='article',
            name='normalized_link',
            field=models.URLField(default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='article',
            name='published_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='articleuserstate',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='tags',
            field=models.ManyToManyField(blank=True, db_table='bookmark_tags', related_name='bookmarks', to='rssapp.tag'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='bookmarkuserstate',
            name='bookmark',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_state', to='rssapp.bookmark'),
        ),
        migrations.AlterField(
            model_name='bookmarkuserstate',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bookmarkuserstate',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(default='#6b7280', max_length=7),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='category',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='extractiontask',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='rssapp.article'),
        ),
        migrations.AlterField(
            model_name='extractiontask',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='extractiontask',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='feed',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='feed',
            name='etag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='feed',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='feed',
            name='last_modified',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='url',
            field=models.URLField(max_length=2048, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(default='#6b7280', max_length=7),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='default_display_mode',
            field=models.CharField(choices=[('list', 'List view'), ('compact', 'Compact view'), ('card', 'Card view')], default='compact', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='articleuserstate',
            constraint=models.UniqueConstraint(fields=('user', 'article'), name='uq_article_user_state'),
        ),
        migrations.AddConstraint(
            model_name='bookmarkuserstate',
            constraint=models.UniqueConstraint(fields=('user', 'bookmark'), name='uq_bookmark_user_state'),
        ),
        migrations.AlterModelTable(
            name='article',
            table='articles',
        ),
        migrations.AlterModelTable(
            name='articleuserstate',
            table='article_user_states',
        ),
        migrations.AlterModelTable(
            name='bookmark',
            table='bookmarks',
        ),
        migrations.AlterModelTable(
            name='bookmarkuserstate',
            table='bookmark_user_states',
        ),
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
        migrations.AlterModelTable(
            name='extractiontask',
            table='extraction_tasks',
        ),
        migrations.AlterModelTable(
            name='feed',
            table='feeds',
        ),
        migrations.AlterModelTable(
            name='tag',
            table='tags',
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='user_profiles',
        ),
        migrations.AddField(
            model_name='readingitem',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reading_items', to='rssapp.article'),
        ),
        migrations.AddField(
            model_name='readingitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='somedayitem',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='someday_items', to='rssapp.article'),
        ),
        migrations.AddField(
            model_name='somedayitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='someday_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscription',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='rssapp.category'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='rssapp.feed'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='BookmarkCategory',
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('user', 'feed'), name='uq_subscription_user_feed'),
        ),
    ]
