# Generated by Django 5.2.12 on 2026-08-15 00:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rssapp', '0019_readingitem_somedayitem_subscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_source',
            field=models.CharField(default='summary', max_length=20),
        ),
        migrations.AddField(
            model_name='article',
            name='extracted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='extraction_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='article',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=2048),
        ),
        migrations.AddField(
            model_name='articleuserstate',
            name='is_favorite',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='articleuserstate',
            name='is_read_later',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='normalized_url',
            field=models.URLField(blank=True, db_index=True, default='', max_length=2048),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='source_article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookmarks', to='rssapp.article'),
        ),
        migrations.AddField(
            model_name='bookmarkuserstate',
            name='is_favorite',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='bookmarkuserstate',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookmarkuserstate',
            name='is_read_later',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='content_type',
            field=models.CharField(default='both', max_length=20),
        ),
        migrations.AddField(
            model_name='feed',
            name='consecutive_failures',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feed',
            name='fetch_interval_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='feed',
            name='last_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='feed',
            name='last_success_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feed',
            name='next_fetch_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
